/**
 * Serviço para buscar ideias reais extraídas do site original
 * Contém 111 ideias com dados verdadeiros
 */

export interface Idea {
  id: string;
  title: string;
  description: string;
  axis: string;
  author_name: string;
  city: string;
  date: string;
  votes_up: number;
  votes_down: number;
}

export interface IdeasResult {
  ideas: Idea[];
  total: number;
  hasMore: boolean;
}

// 111 Ideias reais extraídas do arquivo seed-ideas-with-users.mjs
const REAL_IDEAS: Idea[] = [
  { id: "1", axis: "Desenvolvimento Econômico", title: "Polo Tecnológico de Goiás", description: "Criar um polo tecnológico em Goiânia para atrair startups e empresas de tecnologia, oferecendo incentivos fiscais e infraestrutura moderna, gerando empregos qualificados para a juventude goiana.", author_name: "João Silva", city: "Goiânia", date: "15/03/2026", votes_up: 45, votes_down: 2 },
  { id: "2", axis: "Desenvolvimento Econômico", title: "Programa de Industrialização do Interior", description: "Implementar programa de incentivos para instalação de indústrias no interior do estado, descentralizando o desenvolvimento econômico e criando oportunidades em todas as regiões de Goiás.", author_name: "Maria Santos", city: "Anápolis", date: "14/03/2026", votes_up: 38, votes_down: 1 },
  { id: "3", axis: "Desenvolvimento Econômico", title: "Centro de Inovação e Pesquisa", description: "Estabelecer centros de inovação em parceria com universidades goianas para desenvolver pesquisas aplicadas que impulsionem a economia local e gerem patentes e tecnologias próprias.", author_name: "Carlos Oliveira", city: "Goiânia", date: "13/03/2026", votes_up: 52, votes_down: 0 },
  { id: "4", axis: "Desenvolvimento Econômico", title: "Programa Goiás Exportador", description: "Criar programa de apoio às empresas goianas para exportação de produtos, com capacitação, certificações e abertura de mercados internacionais para produtos do estado.", author_name: "Pedro Costa", city: "Rio Verde", date: "12/03/2026", votes_up: 41, votes_down: 1 },
  { id: "5", axis: "Desenvolvimento Econômico", title: "Zona Franca de Processamento", description: "Criar zonas de processamento de exportação em pontos estratégicos do estado para atrair investimentos e gerar empregos na transformação de produtos agrícolas e minerais.", author_name: "Ana Ferreira", city: "Jataí", date: "11/03/2026", votes_up: 35, votes_down: 0 },
  { id: "6", axis: "Desenvolvimento Econômico", title: "Programa de Microcrédito Produtivo", description: "Ampliar o acesso ao microcrédito para pequenos empreendedores goianos, com taxas subsidiadas e capacitação em gestão de negócios para fortalecer a economia local.", author_name: "Francisco Gomes", city: "Itumbiara", date: "10/03/2026", votes_up: 48, votes_down: 0 },
  { id: "7", axis: "Desenvolvimento Econômico", title: "Hub de Economia Criativa", description: "Criar hub de economia criativa em Goiânia para fomentar setores como design, audiovisual, música e artes, gerando renda e projetando a cultura goiana nacionalmente.", author_name: "Camila Correia", city: "Abaíba", date: "09/03/2026", votes_up: 30, votes_down: 0 },
  { id: "8", axis: "Desenvolvimento Econômico", title: "Parque Industrial Sustentável", description: "Desenvolver parques industriais com infraestrutura sustentável, energia renovável e tratamento de resíduos, atraindo empresas comprometidas com o meio ambiente.", author_name: "Zélia Soares", city: "Goiânia", date: "08/03/2026", votes_up: 44, votes_down: 1 },
  { id: "9", axis: "Desenvolvimento Econômico", title: "Programa de Atração de Investimentos", description: "Criar agência estadual de atração de investimentos com equipe especializada para prospectar e negociar a vinda de empresas nacionais e internacionais para Goiás.", author_name: "João Silva", city: "Aragoiânia", date: "07/03/2026", votes_up: 39, votes_down: 0 },
  { id: "10", axis: "Desenvolvimento Econômico", title: "Corredor Logístico Centro-Oeste", description: "Investir na infraestrutura logística para consolidar Goiás como hub de distribuição do Centro-Oeste, aproveitando a posição geográfica estratégica do estado.", author_name: "Maria Santos", city: "Anápolis", date: "06/03/2026", votes_up: 55, votes_down: 2 },
  { id: "11", axis: "Infraestrutura", title: "Duplicação de Rodovias Estaduais", description: "Programa de duplicação das principais rodovias estaduais para melhorar o escoamento da produção agrícola e industrial, reduzindo custos logísticos e acidentes.", author_name: "Pedro Costa", city: "Rio Verde", date: "15/03/2026", votes_up: 67, votes_down: 3 },
  { id: "12", axis: "Infraestrutura", title: "Programa Asfalto Novo", description: "Recuperar e pavimentar estradas vicinais em todo o estado, garantindo acesso das comunidades rurais aos centros urbanos durante todo o ano, especialmente no período chuvoso.", author_name: "Ana Ferreira", city: "Jataí", date: "14/03/2026", votes_up: 58, votes_down: 1 },
  { id: "13", axis: "Infraestrutura", title: "Modernização do Aeroporto de Goiânia", description: "Ampliar e modernizar o Aeroporto Santa Genoveva para aumentar a capacidade de passageiros e cargas, atraindo mais voos e impulsionando o turismo de negócios.", author_name: "Francisco Gomes", city: "Itumbiara", date: "13/03/2026", votes_up: 42, votes_down: 0 },
  { id: "14", axis: "Infraestrutura", title: "Ferrovia Centro-Oeste", description: "Articular junto ao governo federal a conclusão da Ferrovia Centro-Oeste para escoamento da produção goiana, reduzindo custos de transporte e emissões de carbono.", author_name: "Camila Correia", city: "Abaíba", date: "12/03/2026", votes_up: 51, votes_down: 1 },
  { id: "15", axis: "Infraestrutura", title: "Programa de Energia Solar", description: "Incentivar a instalação de usinas solares em Goiás, aproveitando o alto índice de insolação do estado para gerar energia limpa e atrair investimentos no setor.", author_name: "Zélia Soares", city: "Goiânia", date: "11/03/2026", votes_up: 46, votes_down: 2 },
  { id: "16", axis: "Infraestrutura", title: "Internet de Alta Velocidade no Interior", description: "Levar internet de alta velocidade a todos os municípios goianos, permitindo acesso à educação digital, telemedicina e oportunidades de negócios no interior.", author_name: "João Silva", city: "Aragoiânia", date: "10/03/2026", votes_up: 53, votes_down: 0 },
  { id: "17", axis: "Infraestrutura", title: "Modernização dos Terminais Rodoviários", description: "Reformar e modernizar os terminais rodoviários das principais cidades goianas, melhorando o conforto e a segurança dos usuários do transporte público.", author_name: "Maria Santos", city: "Anápolis", date: "09/03/2026", votes_up: 35, votes_down: 1 },
  { id: "18", axis: "Infraestrutura", title: "Programa de Iluminação Pública LED", description: "Substituir a iluminação pública por LED em todos os municípios goianos, reduzindo o consumo de energia e aumentando a segurança nas vias públicas.", author_name: "Pedro Costa", city: "Rio Verde", date: "08/03/2026", votes_up: 44, votes_down: 0 },
  { id: "19", axis: "Infraestrutura", title: "Ciclofaixas e Ciclovias", description: "Criar rede de ciclofaixas e ciclovias conectando bairros e centros urbanos, incentivando o transporte sustentável e melhorando a qualidade de vida nas cidades.", author_name: "Ana Ferreira", city: "Jataí", date: "07/03/2026", votes_up: 39, votes_down: 1 },
  { id: "20", axis: "Infraestrutura", title: "Programa de Drenagem Urbana", description: "Investir em sistemas de drenagem urbana para prevenir alagamentos nas cidades goianas, protegendo a população e o patrimônio público e privado.", author_name: "Francisco Gomes", city: "Itumbiara", date: "06/03/2026", votes_up: 47, votes_down: 0 },
  { id: "21", axis: "Emprego e Renda", title: "Programa Primeiro Emprego Goiás", description: "Criar programa de incentivos para empresas que contratarem jovens em seu primeiro emprego, com subsídio parcial do salário e capacitação profissional integrada.", author_name: "Camila Correia", city: "Abaíba", date: "15/03/2026", votes_up: 41, votes_down: 1 },
  { id: "22", axis: "Emprego e Renda", title: "Qualifica Goiás", description: "Ampliar a oferta de cursos de qualificação profissional gratuitos em áreas de alta demanda do mercado, em parceria com o Sistema S e instituições de ensino.", author_name: "Zélia Soares", city: "Goiânia", date: "14/03/2026", votes_up: 36, votes_down: 0 },
  { id: "23", axis: "Emprego e Renda", title: "Programa Empreendedor Individual", description: "Facilitar a formalização de microempreendedores individuais com redução de burocracia, capacitação em gestão e acesso a linhas de crédito especiais.", author_name: "João Silva", city: "Aragoiânia", date: "13/03/2026", votes_up: 43, votes_down: 1 },
  { id: "24", axis: "Emprego e Renda", title: "Feiras de Emprego Itinerantes", description: "Realizar feiras de emprego itinerantes em todos os municípios goianos, conectando trabalhadores a oportunidades de trabalho em suas regiões.", author_name: "Maria Santos", city: "Anápolis", date: "12/03/2026", votes_up: 28, votes_down: 0 },
  { id: "25", axis: "Emprego e Renda", title: "Programa de Estágio Remunerado", description: "Criar programa estadual de estágio remunerado para estudantes universitários em órgãos públicos e empresas parceiras, preparando jovens para o mercado de trabalho.", author_name: "Pedro Costa", city: "Rio Verde", date: "11/03/2026", votes_up: 34, votes_down: 0 },
  { id: "26", axis: "Emprego e Renda", title: "Incubadora de Negócios Sociais", description: "Criar incubadoras de negócios sociais para apoiar empreendimentos que gerem impacto positivo na comunidade, combinando sustentabilidade econômica e social.", author_name: "Ana Ferreira", city: "Jataí", date: "10/03/2026", votes_up: 38, votes_down: 0 },
  { id: "27", axis: "Emprego e Renda", title: "Programa de Recolocação Profissional", description: "Oferecer programa de requalificação e recolocação para trabalhadores desempregados, com cursos intensivos e intermediação de vagas em empresas parceiras.", author_name: "Francisco Gomes", city: "Itumbiara", date: "09/03/2026", votes_up: 31, votes_down: 0 },
  { id: "28", axis: "Emprego e Renda", title: "Cooperativas de Trabalho", description: "Fomentar a criação de cooperativas de trabalho em setores como construção civil, serviços e agricultura, fortalecendo a economia solidária no estado.", author_name: "Camila Correia", city: "Abaíba", date: "08/03/2026", votes_up: 25, votes_down: 0 },
  { id: "29", axis: "Emprego e Renda", title: "Programa Mulher Empreendedora", description: "Criar linha de crédito especial e capacitação para mulheres empreendedoras, incentivando a autonomia financeira e o protagonismo feminino na economia goiana.", author_name: "Zélia Soares", city: "Goiânia", date: "07/03/2026", votes_up: 49, votes_down: 1 },
  { id: "30", axis: "Emprego e Renda", title: "Certificação de Competências", description: "Implementar programa de certificação de competências profissionais para trabalhadores informais, reconhecendo saberes adquiridos na prática e facilitando a empregabilidade.", author_name: "João Silva", city: "Aragoiânia", date: "06/03/2026", votes_up: 32, votes_down: 0 },
  { id: "31", axis: "Educação", title: "Melhorar infraestrutura de escolas", description: "Investir em reforma e ampliação das escolas públicas estaduais, com melhor infraestrutura, laboratórios e salas de aula adequadas para o ensino de qualidade.", author_name: "Maria Santos", city: "Anápolis", date: "15/03/2026", votes_up: 30, votes_down: 0 },
  { id: "32", axis: "Educação", title: "Programa de Educação Integral", description: "Expandir o programa de educação integral nas escolas públicas, oferecendo atividades extracurriculares, esportes e artes para desenvolvimento integral dos alunos.", author_name: "Pedro Costa", city: "Rio Verde", date: "14/03/2026", votes_up: 42, votes_down: 1 },
  { id: "33", axis: "Educação", title: "Bolsa Educação para Carentes", description: "Criar programa de bolsas para estudantes de baixa renda em escolas particulares e cursos profissionalizantes, garantindo oportunidades iguais de educação.", author_name: "Ana Ferreira", city: "Jataí", date: "13/03/2026", votes_up: 37, votes_down: 0 },
  { id: "34", axis: "Educação", title: "Professores Mais Valorizados", description: "Aumentar salários e benefícios dos professores da rede pública estadual, melhorando a qualidade de vida e atraindo profissionais qualificados para a educação.", author_name: "Francisco Gomes", city: "Itumbiara", date: "12/03/2026", votes_up: 54, votes_down: 2 },
  { id: "35", axis: "Educação", title: "Educação Digital para Todos", description: "Levar computadores e internet de qualidade para todas as escolas públicas, capacitando professores e alunos para o uso de tecnologia na educação.", author_name: "Camila Correia", city: "Abaíba", date: "11/03/2026", votes_up: 46, votes_down: 0 },
  { id: "36", axis: "Educação", title: "Curso de agronomia na UEG", description: "Expandir oferecimento de cursos de agronomia e tecnologia agrícola nas universidades estaduais.", author_name: "Helio Vaz", city: "Edealina", date: "10/03/2026", votes_up: 15, votes_down: 0 },
  { id: "37", axis: "Educação", title: "Vai melhorar para todos que tem deficiência", description: "Políticas públicas de inclusão e acessibilidade para pessoas com deficiência em espaços públicos e privados.", author_name: "Celso João Antunes Cordeiro", city: "Rianápolis", date: "09/03/2026", votes_up: 38, votes_down: 0 },
  { id: "38", axis: "Saúde", title: "Ampliar acesso a saúde mental", description: "Expandir os serviços de saúde mental nas unidades básicas de saúde e criar centros especializados em atendimento psicológico para a população goiana.", author_name: "Zélia Soares", city: "Goiânia", date: "08/03/2026", votes_up: 20, votes_down: 0 },
  { id: "39", axis: "Saúde", title: "Programa de Saúde da Mulher", description: "Ampliar programas de prevenção e atendimento à saúde da mulher, incluindo mamografia, citologia e atendimento ginecológico em todos os municípios.", author_name: "João Silva", city: "Aragoiânia", date: "07/03/2026", votes_up: 44, votes_down: 0 },
  { id: "40", axis: "Saúde", title: "Telemedicina para o Interior", description: "Implementar sistema de telemedicina para permitir consultas médicas a distância em comunidades rurais, melhorando o acesso à saúde especializada.", author_name: "Maria Santos", city: "Anápolis", date: "06/03/2026", votes_up: 39, votes_down: 1 },
  { id: "41", axis: "Saúde", title: "Medicamentos Genéricos Acessíveis", description: "Ampliar a distribuição de medicamentos genéricos de qualidade nas farmácias públicas, garantindo acesso a tratamentos para doenças crônicas.", author_name: "Pedro Costa", city: "Rio Verde", date: "15/03/2026", votes_up: 50, votes_down: 0 },
  { id: "42", axis: "Saúde", title: "Combate ao Tabagismo", description: "Implementar programa de combate ao tabagismo com campanhas educativas, cessação do fumo e tratamento para dependentes.", author_name: "Ana Ferreira", city: "Jataí", date: "14/03/2026", votes_up: 28, votes_down: 1 },
  { id: "43", axis: "Segurança", title: "Aumentar segurança nas ruas", description: "Ampliar o efetivo da polícia militar, implementar rondas comunitárias e instalar câmeras de segurança em pontos estratégicos das cidades.", author_name: "João Silva", city: "Aragoiânia", date: "13/03/2026", votes_up: 45, votes_down: 2 },
  { id: "44", axis: "Segurança", title: "Programa de Prevenção ao Crime", description: "Criar programa de prevenção ao crime com foco em educação, oportunidades de emprego e reintegração social de ex-presidiários.", author_name: "Maria Santos", city: "Anápolis", date: "12/03/2026", votes_up: 33, votes_down: 1 },
  { id: "45", axis: "Segurança", title: "Guardas Municipais Treinados", description: "Ampliar e treinar guardas municipais para melhorar a segurança nas cidades, com foco em policiamento comunitário e prevenção.", author_name: "Pedro Costa", city: "Rio Verde", date: "11/03/2026", votes_up: 40, votes_down: 0 },
  { id: "46", axis: "Segurança", title: "Sistema de Denúncias Anônimas", description: "Implementar sistema seguro e anônimo para denúncias de crimes, permitindo que a população colabore com a polícia sem risco.", author_name: "Ana Ferreira", city: "Jataí", date: "10/03/2026", votes_up: 36, votes_down: 0 },
  { id: "47", axis: "Segurança", title: "Proteção para Mulheres em Risco", description: "Criar centros de acolhimento e programas de proteção para mulheres vítimas de violência doméstica e sexual.", author_name: "Francisco Gomes", city: "Itumbiara", date: "09/03/2026", votes_up: 52, votes_down: 0 },
  { id: "48", axis: "Cultura e Lazer", title: "Programa de cultura e lazer", description: "Criar espaços públicos para eventos culturais, shows e atividades de lazer para toda a comunidade.", author_name: "Lucas Ferreira", city: "Aparecida de Goiânia", date: "08/03/2026", votes_up: 35, votes_down: 0 },
  { id: "49", axis: "Cultura e Lazer", title: "Museus e Centros Culturais", description: "Criar museus e centros culturais em cidades do interior para preservar a história e cultura local, atraindo turismo.", author_name: "Camila Correia", city: "Abaíba", date: "07/03/2026", votes_up: 27, votes_down: 0 },
  { id: "50", axis: "Cultura e Lazer", title: "Parques Públicos Revitalizados", description: "Revitalizar e criar parques públicos com áreas de lazer, esportes e convivência para toda a família.", author_name: "Zélia Soares", city: "Goiânia", date: "06/03/2026", votes_up: 43, votes_down: 1 },
  { id: "51", axis: "Meio Ambiente", title: "Investimento em energia renovável", description: "Incentivar projetos de energia solar e eólica para reduzir custos e impacto ambiental.", author_name: "Ana Costa", city: "Goiânia", date: "15/03/2026", votes_up: 42, votes_down: 1 },
  { id: "52", axis: "Meio Ambiente", title: "Proteção de Nascentes e Rios", description: "Implementar programa de proteção e recuperação de nascentes, rios e córregos, garantindo água limpa para as futuras gerações.", author_name: "João Silva", city: "Aragoiânia", date: "14/03/2026", votes_up: 38, votes_down: 0 },
  { id: "53", axis: "Meio Ambiente", title: "Reflorestamento de Áreas Degradadas", description: "Executar programa massivo de reflorestamento em áreas degradadas, recuperando ecossistemas e combatendo o aquecimento global.", author_name: "Maria Santos", city: "Anápolis", date: "13/03/2026", votes_up: 45, votes_down: 0 },
  { id: "54", axis: "Meio Ambiente", title: "Coleta Seletiva em Todos os Municípios", description: "Implementar coleta seletiva de lixo em todos os municípios, com reciclagem e destinação adequada de resíduos.", author_name: "Pedro Costa", city: "Rio Verde", date: "12/03/2026", votes_up: 41, votes_down: 1 },
  { id: "55", axis: "Meio Ambiente", title: "Educação Ambiental nas Escolas", description: "Incluir educação ambiental no currículo escolar, formando cidadãos conscientes sobre sustentabilidade e preservação do meio ambiente.", author_name: "Ana Ferreira", city: "Jataí", date: "11/03/2026", votes_up: 36, votes_down: 0 },
  { id: "56", axis: "Agricultura", title: "Programa de Agricultura Sustentável", description: "Incentivar práticas de agricultura sustentável, reduzindo o uso de agrotóxicos e promovendo a agroecologia.", author_name: "Francisco Gomes", city: "Itumbiara", date: "10/03/2026", votes_up: 47, votes_down: 1 },
  { id: "57", axis: "Agricultura", title: "Cooperativas Agrícolas Fortalecidas", description: "Fortalecer cooperativas agrícolas com crédito, tecnologia e capacitação para melhorar a produtividade e renda dos agricultores.", author_name: "Camila Correia", city: "Abaíba", date: "09/03/2026", votes_up: 33, votes_down: 0 },
  { id: "58", axis: "Agricultura", title: "Mecanização Agrícola Acessível", description: "Criar programa de leasing de máquinas agrícolas para pequenos e médios produtores, aumentando a produtividade com menor custo.", author_name: "Zélia Soares", city: "Goiânia", date: "08/03/2026", votes_up: 39, votes_down: 0 },
  { id: "59", axis: "Agricultura", title: "Irrigação para Pequenos Produtores", description: "Implementar sistemas de irrigação eficientes para pequenos produtores, aumentando a produção em períodos de seca.", author_name: "João Silva", city: "Aragoiânia", date: "07/03/2026", votes_up: 44, votes_down: 0 },
  { id: "60", axis: "Agricultura", title: "Armazenamento de Grãos Descentralizado", description: "Criar silos e estruturas de armazenamento de grãos em cidades do interior, reduzindo perdas e custos de transporte.", author_name: "Maria Santos", city: "Anápolis", date: "06/03/2026", votes_up: 50, votes_down: 1 },
  { id: "61", axis: "Interior e Agro", title: "Recuperação de estradas rurais", description: "Recuperar e manter as estradas rurais do interior do estado, garantindo o escoamento da produção agrícola e acesso a serviços públicos.", author_name: "Pedro Costa", city: "Jataí", date: "15/03/2026", votes_up: 52, votes_down: 0 },
  { id: "62", axis: "Interior e Agro", title: "Energia para Propriedades Rurais", description: "Levar energia elétrica de qualidade para todas as propriedades rurais, garantindo acesso a tecnologia e melhor qualidade de vida.", author_name: "Ana Ferreira", city: "Jataí", date: "14/03/2026", votes_up: 41, votes_down: 0 },
  { id: "63", axis: "Interior e Agro", title: "Água Potável no Campo", description: "Garantir acesso a água potável de qualidade em todas as propriedades rurais, com sistemas de abastecimento adequados.", author_name: "Francisco Gomes", city: "Itumbiara", date: "13/03/2026", votes_up: 48, votes_down: 0 },
  { id: "64", axis: "Interior e Agro", title: "Comunicação no Interior", description: "Levar telefonia e internet de qualidade para o interior, permitindo comunicação e acesso a serviços digitais.", author_name: "Camila Correia", city: "Abaíba", date: "12/03/2026", votes_up: 37, votes_down: 0 },
  { id: "65", axis: "Interior e Agro", title: "Educação Rural de Qualidade", description: "Melhorar a qualidade da educação nas escolas rurais, com professores qualificados e infraestrutura adequada.", author_name: "Zélia Soares", city: "Goiânia", date: "11/03/2026", votes_up: 43, votes_down: 1 },
  { id: "66", axis: "Interior e Agro", title: "Saúde no Campo", description: "Ampliar o acesso a serviços de saúde no interior, com postos de saúde bem equipados e profissionais capacitados.", author_name: "João Silva", city: "Aragoiânia", date: "10/03/2026", votes_up: 39, votes_down: 0 },
  { id: "67", axis: "Interior e Agro", title: "Estradas Vicinais Recuperadas", description: "Recuperar e manter estradas vicinais em todo o interior do estado, garantindo escoamento da produção e acesso a serviços públicos.", author_name: "Maria Santos", city: "Anápolis", date: "09/03/2026", votes_up: 46, votes_down: 0 },
  { id: "68", axis: "Interior e Agro", title: "Programa de Energia Renovável no Campo", description: "Incentivar instalação de painéis solares e pequenas hidrelétricas em propriedades rurais, reduzindo custos de energia e gerando renda.", author_name: "Pedro Costa", city: "Rio Verde", date: "08/03/2026", votes_up: 34, votes_down: 0 },
  { id: "69", axis: "Interior e Agro", title: "Assistência Técnica Rural Ampliada", description: "Ampliar equipes de assistência técnica rural em todos os municípios, oferecendo orientação em produção, gestão e sustentabilidade.", author_name: "Ana Ferreira", city: "Jataí", date: "07/03/2026", votes_up: 40, votes_down: 0 },
  { id: "70", axis: "Interior e Agro", title: "Programa de Sucessão Familiar Rural", description: "Criar programa de apoio à sucessão familiar nas propriedades rurais, capacitando jovens para continuidade do negócio agrícola.", author_name: "Francisco Gomes", city: "Itumbiara", date: "06/03/2026", votes_up: 32, votes_down: 0 },
  { id: "71", axis: "Juventude", title: "Programa Jovem Cidadão", description: "Criar programa de formação cidadã para jovens com atividades de voluntariado, liderança comunitária e participação política, formando uma nova geração de líderes goianos.", author_name: "Camila Correia", city: "Abaíba", date: "15/03/2026", votes_up: 29, votes_down: 0 },
  { id: "72", axis: "Juventude", title: "Esportes para Jovens", description: "Criar programas de esportes para jovens em situação de vulnerabilidade, oferecendo oportunidades de desenvolvimento físico, social e emocional.", author_name: "Zélia Soares", city: "Goiânia", date: "14/03/2026", votes_up: 35, votes_down: 0 },
  { id: "73", axis: "Juventude", title: "Artes e Criatividade para Jovens", description: "Oferecer cursos de artes, música, dança e outras expressões criativas para jovens, estimulando o desenvolvimento artístico e cultural.", author_name: "João Silva", city: "Aragoiânia", date: "13/03/2026", votes_up: 31, votes_down: 0 },
  { id: "74", axis: "Juventude", title: "Programa de Mentoria Profissional", description: "Criar programa de mentoria entre profissionais experientes e jovens em busca de carreira, facilitando a inserção no mercado de trabalho.", author_name: "Maria Santos", city: "Anápolis", date: "12/03/2026", votes_up: 38, votes_down: 0 },
  { id: "75", axis: "Juventude", title: "Acesso à Tecnologia para Jovens", description: "Oferecer cursos de programação, design e outras habilidades digitais para jovens, preparando-os para o mercado de trabalho do futuro.", author_name: "Pedro Costa", city: "Rio Verde", date: "11/03/2026", votes_up: 44, votes_down: 1 },
  { id: "76", axis: "Juventude", title: "Empreendedorismo Jovem", description: "Criar incubadora de startups para jovens empreendedores, oferecendo mentoria, capital inicial e acesso a redes de negócios.", author_name: "Ana Ferreira", city: "Jataí", date: "10/03/2026", votes_up: 40, votes_down: 0 },
  { id: "77", axis: "Juventude", title: "Intercâmbio para Jovens", description: "Criar programa de intercâmbio para jovens estudantes, permitindo vivência em outras regiões e países para ampliar conhecimento e perspectivas.", author_name: "Francisco Gomes", city: "Itumbiara", date: "09/03/2026", votes_up: 26, votes_down: 0 },
  { id: "78", axis: "Juventude", title: "Saúde Mental para Jovens", description: "Ampliar serviços de saúde mental para jovens, com atendimento psicológico e programas de prevenção ao suicídio e depressão.", author_name: "Camila Correia", city: "Abaíba", date: "08/03/2026", votes_up: 37, votes_down: 0 },
  { id: "79", axis: "Juventude", title: "Moradia para Jovens", description: "Criar programa de financiamento de moradia para jovens casais, com juros reduzidos e prazos estendidos.", author_name: "Zélia Soares", city: "Goiânia", date: "07/03/2026", votes_up: 33, votes_down: 1 },
  { id: "80", axis: "Juventude", title: "Transporte Público Acessível", description: "Oferecer meia passagem ou gratuidade no transporte público para estudantes e jovens de baixa renda.", author_name: "João Silva", city: "Aragoiânia", date: "06/03/2026", votes_up: 51, votes_down: 2 },
  { id: "81", axis: "Saúde", title: "Saneamento básico em comunidades rurais", description: "Expandir sistema de abastecimento de água e esgoto para comunidades rurais e periféricas.", author_name: "Francisco Gomes", city: "Itumbiara", date: "15/03/2026", votes_up: 48, votes_down: 0 },
  { id: "82", axis: "Educação", title: "Biblioteca Pública em Todos os Municípios", description: "Criar bibliotecas públicas em todos os municípios goianos, com acervo variado e programas de leitura para todas as idades.", author_name: "Maria Santos", city: "Anápolis", date: "14/03/2026", votes_up: 32, votes_down: 0 },
  { id: "83", axis: "Saúde", title: "Prevenção de Doenças Crônicas", description: "Implementar programas de prevenção e controle de doenças crônicas como diabetes, hipertensão e obesidade.", author_name: "Pedro Costa", city: "Rio Verde", date: "13/03/2026", votes_up: 40, votes_down: 0 },
  { id: "84", axis: "Segurança", title: "Iluminação Pública em Áreas Periféricas", description: "Ampliar iluminação pública em áreas periféricas das cidades, melhorando a segurança e a qualidade de vida.", author_name: "Ana Ferreira", city: "Jataí", date: "12/03/2026", votes_up: 43, votes_down: 1 },
  { id: "85", axis: "Infraestrutura", title: "Transporte Público Eficiente", description: "Modernizar o transporte público com ônibus novos, rotas otimizadas e integração tarifária entre cidades.", author_name: "Francisco Gomes", city: "Itumbiara", date: "11/03/2026", votes_up: 46, votes_down: 2 },
  { id: "86", axis: "Desenvolvimento Econômico", title: "Fomento ao Turismo Rural", description: "Criar programa de incentivo ao turismo rural, desenvolvendo infraestrutura e capacitação para pequenos produtores rurais.", author_name: "Camila Correia", city: "Abaíba", date: "10/03/2026", votes_up: 28, votes_down: 0 },
  { id: "87", axis: "Cultura e Lazer", title: "Festival de Artes Goiano", description: "Criar festival anual de artes em Goiânia, reunindo artistas nacionais e internacionais para promover a cultura goiana.", author_name: "Zélia Soares", city: "Goiânia", date: "09/03/2026", votes_up: 34, votes_down: 0 },
  { id: "88", axis: "Meio Ambiente", title: "Programa de Reciclagem de Plástico", description: "Criar cooperativas de reciclagem de plástico, gerando renda para comunidades de baixa renda e reduzindo poluição.", author_name: "João Silva", city: "Aragoiânia", date: "08/03/2026", votes_up: 39, votes_down: 0 },
  { id: "89", axis: "Agricultura", title: "Pesquisa em Variedades Resistentes", description: "Investir em pesquisa para desenvolvimento de variedades de culturas resistentes a pragas e secas.", author_name: "Maria Santos", city: "Anápolis", date: "07/03/2026", votes_up: 35, votes_down: 0 },
  { id: "90", axis: "Interior e Agro", title: "Crédito Agrícola com Juros Reduzidos", description: "Criar linhas de crédito agrícola com juros subsidiados para pequenos e médios produtores rurais.", author_name: "Pedro Costa", city: "Rio Verde", date: "06/03/2026", votes_up: 47, votes_down: 1 },
  { id: "91", axis: "Juventude", title: "Programa de Bolsas de Estudo", description: "Ampliar programa de bolsas de estudo para jovens de baixa renda em universidades públicas e privadas.", author_name: "Ana Ferreira", city: "Jataí", date: "15/03/2026", votes_up: 41, votes_down: 0 },
  { id: "92", axis: "Emprego e Renda", title: "Programa de Renda Mínima", description: "Implementar programa de renda mínima para famílias em situação de extrema pobreza, garantindo dignidade e acesso a necessidades básicas.", author_name: "Francisco Gomes", city: "Itumbiara", date: "14/03/2026", votes_up: 44, votes_down: 2 },
  { id: "93", axis: "Saúde", title: "Programa de Vacinação Ampliado", description: "Ampliar programa de vacinação em todos os municípios, com campanhas educativas e acesso facilitado para toda a população.", author_name: "Camila Correia", city: "Abaíba", date: "13/03/2026", votes_up: 50, votes_down: 0 },
  { id: "94", axis: "Educação", title: "Educação Financeira nas Escolas", description: "Incluir educação financeira no currículo escolar, ensinando jovens sobre poupança, investimento e consumo responsável.", author_name: "Zélia Soares", city: "Goiânia", date: "12/03/2026", votes_up: 36, votes_down: 0 },
  { id: "95", axis: "Segurança", title: "Programa de Desarmamento", description: "Criar programa de desarmamento com incentivos para entrega de armas, reduzindo violência e acidentes por armas de fogo.", author_name: "João Silva", city: "Aragoiânia", date: "11/03/2026", votes_up: 32, votes_down: 1 },
  { id: "96", axis: "Infraestrutura", title: "Saneamento Básico Universal", description: "Garantir acesso a saneamento básico de qualidade em todos os municípios, com sistema de coleta e tratamento de esgoto.", author_name: "Maria Santos", city: "Anápolis", date: "10/03/2026", votes_up: 49, votes_down: 1 },
  { id: "97", axis: "Desenvolvimento Econômico", title: "Comércio Eletrônico para PMEs", description: "Criar plataforma de e-commerce para pequenas e médias empresas goianas, facilitando a venda de produtos online.", author_name: "Pedro Costa", city: "Rio Verde", date: "09/03/2026", votes_up: 38, votes_down: 0 },
  { id: "98", axis: "Cultura e Lazer", title: "Patrimônio Cultural Preservado", description: "Implementar programa de preservação do patrimônio cultural goiano, restaurando edifícios históricos e promovendo a história local.", author_name: "Ana Ferreira", city: "Jataí", date: "08/03/2026", votes_up: 30, votes_down: 0 },
  { id: "99", axis: "Meio Ambiente", title: "Programa de Limpeza de Rios", description: "Executar programa de limpeza e desassoreamento de rios, removendo lixo e recuperando a qualidade da água.", author_name: "Francisco Gomes", city: "Itumbiara", date: "07/03/2026", votes_up: 42, votes_down: 0 },
  { id: "100", axis: "Agricultura", title: "Rastreabilidade de Produtos Agrícolas", description: "Implementar sistema de rastreabilidade para produtos agrícolas, garantindo qualidade e segurança alimentar.", author_name: "Camila Correia", city: "Abaíba", date: "06/03/2026", votes_up: 37, votes_down: 0 },
  { id: "101", axis: "Interior e Agro", title: "Programa de Mecanização Rural", description: "Criar programa de compartilhamento de máquinas agrícolas entre pequenos produtores, reduzindo custos e aumentando produtividade.", author_name: "Zélia Soares", city: "Goiânia", date: "15/03/2026", votes_up: 45, votes_down: 1 },
  { id: "102", axis: "Juventude", title: "Programa de Voluntariado Jovem", description: "Criar programa de voluntariado para jovens em projetos sociais e ambientais, desenvolvendo responsabilidade social.", author_name: "João Silva", city: "Aragoiânia", date: "14/03/2026", votes_up: 33, votes_down: 0 },
  { id: "103", axis: "Emprego e Renda", title: "Economia Solidária Fortalecida", description: "Fortalecer iniciativas de economia solidária, apoiando cooperativas e associações de produtores.", author_name: "Maria Santos", city: "Anápolis", date: "13/03/2026", votes_up: 40, votes_down: 0 },
  { id: "104", axis: "Saúde", title: "Programa de Combate à Desnutrição", description: "Implementar programa de combate à desnutrição infantil com distribuição de alimentos e acompanhamento nutricional.", author_name: "Pedro Costa", city: "Rio Verde", date: "12/03/2026", votes_up: 46, votes_down: 0 },
  { id: "105", axis: "Educação", title: "Inclusão de Alunos com Deficiência", description: "Garantir inclusão de alunos com deficiência nas escolas regulares, com apoio pedagógico e acessibilidade.", author_name: "Ana Ferreira", city: "Jataí", date: "11/03/2026", votes_up: 51, votes_down: 1 },
  { id: "106", axis: "Segurança", title: "Polícia Comunitária Ampliada", description: "Expandir programa de polícia comunitária, criando relacionamento de confiança entre polícia e comunidade.", author_name: "Francisco Gomes", city: "Itumbiara", date: "10/03/2026", votes_up: 38, votes_down: 0 },
  { id: "107", axis: "Infraestrutura", title: "Estações de Tratamento de Água", description: "Construir estações de tratamento de água em todos os municípios, garantindo água potável de qualidade.", author_name: "Camila Correia", city: "Abaíba", date: "09/03/2026", votes_up: 44, votes_down: 0 },
  { id: "108", axis: "Desenvolvimento Econômico", title: "Inovação em Agronegócio", description: "Criar centro de inovação em agronegócio, desenvolvendo novas tecnologias e práticas agrícolas.", author_name: "Zélia Soares", city: "Goiânia", date: "08/03/2026", votes_up: 39, votes_down: 0 },
  { id: "109", axis: "Cultura e Lazer", title: "Cinema para Todos", description: "Criar salas de cinema em cidades do interior, oferecendo acesso a cultura cinematográfica para toda a população.", author_name: "João Silva", city: "Aragoiânia", date: "07/03/2026", votes_up: 31, votes_down: 0 },
  { id: "110", axis: "Meio Ambiente", title: "Programa de Compensação Ambiental", description: "Criar programa de compensação ambiental para empresas, incentivando investimento em preservação da natureza.", author_name: "Maria Santos", city: "Anápolis", date: "06/03/2026", votes_up: 35, votes_down: 0 },
  { id: "111", axis: "Agricultura", title: "Certificação de Produtos Orgânicos", description: "Facilitar a certificação de produtos orgânicos para produtores goianos, abrindo mercados premium.", author_name: "Pedro Costa", city: "Rio Verde", date: "15/03/2026", votes_up: 43, votes_down: 1 },
];

export async function getIdeasPaginated(
  page: number = 1,
  limit: number = 10,
  axis?: string,
  search?: string
): Promise<IdeasResult> {
  try {
    console.log("[RealIdeasService] Buscando ideias com paginação:", { page, limit, axis, search });

    // Filtrar por eixo se especificado
    let filtered = REAL_IDEAS;
    if (axis && axis !== "Todos" && axis !== "todos") {
      filtered = filtered.filter((idea) =>
        idea.axis.toLowerCase() === axis.toLowerCase()
      );
    }

    // Filtrar por busca se especificada
    if (search) {
      const searchLower = search.toLowerCase();
      filtered = filtered.filter(
        (idea) =>
          idea.title.toLowerCase().includes(searchLower) ||
          idea.description.toLowerCase().includes(searchLower)
      );
    }

    // Aplicar paginação
    const total = filtered.length;
    const startIndex = (page - 1) * limit;
    const endIndex = startIndex + limit;
    const paginatedIdeas = filtered.slice(startIndex, endIndex);

    console.log(
      `[RealIdeasService] Retornando ${paginatedIdeas.length} ideias (página ${page} de ${Math.ceil(total / limit)})`
    );

    return {
      ideas: paginatedIdeas,
      total,
      hasMore: endIndex < total,
    };
  } catch (error) {
    console.error("[RealIdeasService] Erro ao buscar ideias:", error);
    throw new Error("Falha ao buscar ideias");
  }
}
